[tool.poetry]
name = "pyproject-toml"
version = "0.1.0"
description = ""
authors = ["Marina Berdnikova <berdni4ka@rambler.ru>"]
readme = "README.md"
packages = [{include = "pyproject"}]

[tool.poetry.dependencies]
python = "^3.8"


[tool.poetry.group.dev.dependencies]
pytest = "^7.2.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
